[theme]
primaryColor = "#0F5EDD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFF"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

